version: '3.9'
services:
  kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1.19.6
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - uptime-kuma:/app/data

  api:
    container_name: backend
    # image: medaziz11/uptimekuma_restapi
    build: .
    volumes:
      - ./db:/db
    restart: always
    environment:
      - KUMA_SERVER=http://kuma:3001
      - KUMA_USERNAME=test
      - KUMA_PASSWORD=123test.
      - ADMIN_PASSWORD=admin
      - ACCESS_TOKEN_EXPIRATION=1 #1minute
    depends_on:
      - kuma
    ports:
      - "8000:8000"

volumes:
  uptime-kuma:
